version: "3.8"

services:
  backend:
    build:
      context: ./backend-hello
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  ding:
    build:
      context: ./backend-chat
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
    env_file:
      - ./backend-chat/.env.local
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:3000
      - DING_URL=http://ding:5200
